version: '3.8'

name: HotSoupContainers
services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - HotSoup_Backend_Network
  database:
    container_name: HotSoupPrimaryDb
    image: 'mongo:latest'
    env_file:
      - ./.env.dev
    volumes:
      - ./.volumes/mongodb/data/db:/data/db
    ports:
      - '${MONGO_PORT:-27017}-27019:${MONGO_PORT:-27017}-27019'
    networks:
      - HotSoup_Backend_Network
networks:
  HotSoup_Backend_Network:
    name: "hotsoup_backend_network"
